### ISSUE TITLE
How to check the number of A-B bonds in sqsgenerator

### ISSUE THREAD

**Issue by QQQsupermans** [dgehringer/sqsgenerator#28]
Hi, 
Thanks a lot for your previous help. I have another question now. When I can get a structure, I use "sqsgenerator alpha sqs POSCAR --weight=1 --verbosity=3" to get the  short-range-order (SRO). However, I find slight changes the distance of one A-B bond (just 0.0001 Ångstrom) lead to different SRO values. 

The difference may be due to the precision of lattice vector and atomic fractional coordinate. I want to know the precision, and how to get the number of A-B bonds in "sqsgenerator" to check the SRO values.

Thank you!

**Comment by dgehringer** [comment]
Hi @QQQsupermans 

At first I strongly encourage you to update sqsgenerator to the current version version!
With the new version it should be easier to accomplish what you intend to do, or something similar at least! 

### count bonds
As the SRO parameters are defined as

$$
\alpha^i_{\xi\eta} = 1 - \dfrac{N^i_{\xi\eta}}{NM^ix_{\xi}x_{\eta}}
$$

you want to "*extract*" $N^i_{\xi\eta}$. The new version of sqsgenerator allows you to set the value of the denominator, by rewriting the above equation to $\alpha^i_{\xi\eta} = 1 - f^i_{\xi\eta}N^i_{\xi\eta}$ where $f_{\xi\eta}^i = (NM^ix_\xi x_\eta)^{-1}$.
Hence, by setting $f^i_{\xi\eta} = -1$ we obtain $\tilde{\alpha}^i_{\xi\eta} = 1 + N^i_{\xi\eta}$ (number of bonds plus one). You find more details [here](https://sqsgenerator.readthedocs.io/en/latest/what_is_actually_computed.html#putting-it-all-together) and [here](https://sqsgenerator.readthedocs.io/en/latest/input_parameters.html#prefactors).

Hence create a YAML file

```yaml
structure:
  file: path/to/your/structure_file
prefactors: -1.0
```

from the outputed numbers you then have to subtract one to obtain the number of bonds (pairs) in the shell.
You can then analyse you structure using

```bash
sqsgen analyse sqs.yaml -of yaml
```

The output should look something like the following

```yaml
configurations:
  4082:
    configuration: [W, Re, W, Re, W, Re, W, Re, W, Re, W, Re, W, Re, W, Re]
    objective: 66.08333333333334
    parameters:
    - - [1.0, 65.0]
      - [65.0, 1.0]
    - - [13.0, 1.0]
      - [1.0, 13.0]
    - - [13.0, 1.0]
      - [1.0, 13.0]
    - - [5.0, 1.0]
      - [1.0, 5.0]
```

This means there are 0 "W-W", 64 "W-Re" and 0 "Re-Re" bonds in the example structure.

### slight changes the distance
You can handle this deviations from the perfect lattice in two ways

1.) Increase the tolerances [`atol`](https://sqsgenerator.readthedocs.io/en/latest/input_parameters.html#atol) or [`rtol`](https://sqsgenerator.readthedocs.io/en/latest/input_parameters.html#rtol) used to compute the coordination shell radii.

2.) Or explicitly set the radii of the coordination shell by setting the [`shell_distances`](https://sqsgenerator.readthedocs.io/en/latest/input_parameters.html#shell-distances) parameters.

```yaml
shell_distances: [0.0, 2.75, 3.165, 4.475, 5.49]
```

I hope this answers your questions
