### ISSUE TITLE
Dear maintainer. This is a nice work. Congrats! It's pleasing to hear that the project is evolving.

### ISSUE THREAD

**Issue by dgehringer** [dgehringer/sqsgenerator#50]
Dear maintainer. This is a nice work. Congrats! It's pleasing to hear that the project is evolving. 

I have doubts about the use of some functions when generating the SQS. I don't know if there is a better channel for the present discussion; please let me know. Anyway, here is my issue: I'm trying to generate the SQS for a ZnO Wurtizite structure with some Zn atoms changed by Ag. I created a 3x3x2 supercell with 72 atoms and instructed the code to add 3 Ag atoms to the Zn sites. I read in the documentation the necessity of adding pair_weights, but I didn't get how to define the atoms' order to build the matrix. Here is my yaml input:

```
structure:
  supercell: [3, 3, 2]
  file: ZnO.cif
mode: random
iterations: 1e7
shell_weights:
  2: 1.0
  3: 0.5
  4: 0.25
  5: 0.2
  6: 0.1667
  7: 0.1429
#which: Zn
composition:
  Zn: 
    Zn: 33
  Ag: 
    Zn: 3
  O: 
    O: 36  
prefactor_mode: mul
prefactors: 0.5
pair_weights:
  #   O      Ag     Zn 
  - [ 0.0,   0.0 , 0.0] # O
  - [ 0.0,   0.0,  0.5 ] # Ag
  - [ 0.0,   0.5,  0.0 ] # Zn
```
I'm using 0.5 following the example. Does it hold even for the unbalanced number of atoms (33 Zn and 3 Ag)?

Should I always include the parameter "supercell" in the input to force the code to generate structures as supercells? I mean, in the ATAT SQS code, we just need to inform the number of atoms, not necessarily the supercell.

Thanks in advance.

_Originally posted by @anibalbezerra in https://github.com/dgehringer/sqsgenerator/discussions/48#discussioncomment-11472293_

**Comment by dgehringer** [comment]
Hi @anibalbezerra

I have transferred your question to this issue!

Indeed @dhoulek is right. The matrix indices are referring to the ordinal numbers of the atomic species in ascending order.

I admit however, that it might not be straightforward to find. The information you are looking for is in the [target_ojective](https://sqsgenerator.readthedocs.io/en/latest/input_parameters.html#target-objective) parameter setting . There you have to open the card *A note on array input interpretation*. There is just a reference to it in the [pair_weights](A note on array input interpretation) parameter's section.

There is also a note named *Input array interpretations* at very to of the [input parameter](https://sqsgenerator.readthedocs.io/en/latest/input_parameters.html) documentation page which should help.


Coming back to your question!

The *supercell* argument's default value is 1,1,1. So if your file `ZnO.cif` contains 72 atoms you can leave the *supercell* argument away. In case it has 4 atoms you need to specify the *supercell*. The *supercell* tag is meant as a convenience function.

As you are turning of in your example the sub lattice - sub lattice interactions. I'd suggest the following simplified YAML (assuming `ZnO.cif` contains 4 atoms) ($4 \times 3 \times 3 \times 2 = 72$ atoms)

```yaml
structure:
  supercell: [3, 3, 2]  # just delete this line in case ZnO.cif has 72 atoms
  file: ZnO.cif
mode: random
iterations: 1e7
shell_weights:
  2: 1.0
  3: 0.5
  4: 0.25
  5: 0.2
  6: 0.1667
  7: 0.1429
which: Zn
composition:
  Zn: 33
  Ag: 3
```

I hope that helps!

Let me know if this does what you expect
Best regards
